use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
  emit_sidecar_file_count_budget();
  emit_discord_application_id();
  tauri_build::build()
}

/// Supply `COVENCAVE_DISCORD_APPLICATION_ID` so local builds get Rich Presence.
///
/// `discord_presence.rs` reads this through `option_env!`, which resolves at
/// compile time. A build that does not see the variable bakes in
/// `DISCORD_APPLICATION_ID = None` and can never publish activity, and nothing
/// at runtime can repair it. Until now only `release.yml` passed the variable,
/// so every local `cargo build` / `pnpm dev:app` / `tauri build` produced a
/// presence-less binary that is indistinguishable from a working one — the sole
/// signal is one log line, and on Windows release builds
/// `windows_subsystem = "windows"` means there is no console to print it to.
///
/// Defaulting here removes that trap. The ID is public: it ships inside every
/// binary, Discord serves it from an unauthenticated endpoint, and
/// `release.yml` already carries it in a comment.
///
/// An explicit variable still wins, so CI and forks pointing at their own
/// application are unaffected. Setting it to the empty string is an explicit
/// opt-out and keeps the "not configured" branch reachable.
///
/// Unlike the budget above, a missing value here is not a correctness hazard —
/// it degrades one cosmetic integration — so this defaults rather than panics.
fn emit_discord_application_id() {
  const DEFAULT_APPLICATION_ID: &str = "1529254721091801180";

  // `option_env!` alone never triggers a rebuild when the variable changes;
  // only a build script declaring the dependency does.
  println!("cargo:rerun-if-env-changed={DISCORD_APPLICATION_ID_VAR}");

  let application_id = env::var(DISCORD_APPLICATION_ID_VAR)
    .unwrap_or_else(|_| DEFAULT_APPLICATION_ID.to_string());
  println!("cargo:rustc-env={DISCORD_APPLICATION_ID_VAR}={application_id}");
}

const DISCORD_APPLICATION_ID_VAR: &str = "COVENCAVE_DISCORD_APPLICATION_ID";

/// Generate `MAX_FILE_COUNT` from `scripts/sidecar-runtime-budget.json`.
///
/// This const used to be typed out as a literal in `sidecar_archive_manifest.rs`
/// and kept in step with the JS closure script by hand. It drifted: #4249
/// reverted it downward on its own while the JS side stayed put, and every raise
/// since has been a multi-file sync performed against a red CI. Generating it
/// means the Rust extractor and the packaging gate cannot disagree — there is
/// one number, in one file (cave-0ia8h).
///
/// Every failure path here panics. A build that cannot read its budget must not
/// fall back to a default: a silently permissive `MAX_FILE_COUNT` would relax
/// the archive-extraction bound, which is a decompression-bomb guard rather than
/// merely a size gate.
fn emit_sidecar_file_count_budget() {
  let budget_path = Path::new("..").join("scripts").join("sidecar-runtime-budget.json");
  println!("cargo:rerun-if-changed={}", budget_path.display());

  let raw = fs::read_to_string(&budget_path).unwrap_or_else(|error| {
    panic!("sidecar runtime budget is unreadable at {}: {error}", budget_path.display())
  });
  let parsed: serde_json::Value = serde_json::from_str(&raw).unwrap_or_else(|error| {
    panic!("sidecar runtime budget at {} is not valid JSON: {error}", budget_path.display())
  });
  let file_count = parsed
    .get("fileCount")
    .and_then(serde_json::Value::as_u64)
    .unwrap_or_else(|| {
      panic!(
        "sidecar runtime budget at {} must carry a positive integer \"fileCount\"",
        budget_path.display()
      )
    });
  assert!(file_count > 0, "sidecar runtime budget \"fileCount\" must be greater than zero");

  let out_dir = env::var("OUT_DIR").expect("cargo always sets OUT_DIR for build scripts");
  let destination = PathBuf::from(out_dir).join("sidecar_file_count_budget.rs");
  fs::write(
    &destination,
    format!(
      "// @generated by build.rs from scripts/sidecar-runtime-budget.json — do not edit.\n\
       pub(super) const MAX_FILE_COUNT: u64 = {file_count};\n"
    ),
  )
  .unwrap_or_else(|error| panic!("could not write {}: {error}", destination.display()));
}
