// GENERATED by scripts/sync-model-catalog.mjs - do not edit by hand.
// Re-generate with: node scripts/sync-model-catalog.mjs
//
// Source: config/runtime-model-catalog.json
// sha256: bc98df0212b96b69bcfe8b54828768e1174b725ffdd9b78e018b1d8d4e837806

export const MODEL_CATALOG_SOURCE = {
  schemaVersion: 1,
  sha256: "bc98df0212b96b69bcfe8b54828768e1174b725ffdd9b78e018b1d8d4e837806",
} as const;

export type GeneratedRuntimeProvider =
  | "openai"
  | "anthropic"
  | "github"
  | "nous"
  | "xai"
  | null;

export type GeneratedRuntimeModelCatalog = {
  runtime: string;
  provider: GeneratedRuntimeProvider;
  models: Array<{ id: string; label: string }>;
  defaultModel?: string;
  allowCustom: boolean;
  defaultOwner: "cave" | "runtime";
};

export const GENERATED_RUNTIME_MODEL_CATALOG: Record<
  string,
  GeneratedRuntimeModelCatalog
> = {
  "codex": {
    "runtime": "codex",
    "provider": "openai",
    "models": [
      {
        "id": "openai/gpt-5.6-sol",
        "label": "GPT-5.6 Sol"
      },
      {
        "id": "openai/gpt-6-astra",
        "label": "GPT-6 Astra"
      },
      {
        "id": "openai/gpt-5.6-terra",
        "label": "GPT-5.6 Terra"
      },
      {
        "id": "openai/gpt-5.6-luna",
        "label": "GPT-5.6 Luna"
      },
      {
        "id": "openai/gpt-5.5",
        "label": "GPT-5.5"
      },
      {
        "id": "openai/gpt-5.4",
        "label": "GPT-5.4"
      },
      {
        "id": "openai/gpt-5.4-mini",
        "label": "GPT-5.4 Mini"
      },
      {
        "id": "openai/gpt-5.3-codex-spark",
        "label": "GPT-5.3 Codex Spark"
      }
    ],
    "allowCustom": true,
    "defaultOwner": "cave"
  },
  "claude": {
    "runtime": "claude",
    "provider": "anthropic",
    "models": [
      {
        "id": "anthropic/claude-opus-4-8",
        "label": "Claude Opus 4.8"
      },
      {
        "id": "anthropic/claude-fable-5-1",
        "label": "Claude Fable 5.1"
      },
      {
        "id": "anthropic/claude-fable-5",
        "label": "Claude Fable 5"
      },
      {
        "id": "anthropic/claude-opus-4-7",
        "label": "Claude Opus 4.7"
      },
      {
        "id": "anthropic/claude-sonnet-5",
        "label": "Claude Sonnet 5"
      },
      {
        "id": "anthropic/claude-sonnet-4-6",
        "label": "Claude Sonnet 4.6"
      },
      {
        "id": "anthropic/claude-haiku-4-5",
        "label": "Claude Haiku 4.5"
      }
    ],
    "allowCustom": true,
    "defaultOwner": "cave"
  },
  "copilot": {
    "runtime": "copilot",
    "provider": "github",
    "models": [
      {
        "id": "github/auto",
        "label": "Auto (Copilot picks)"
      },
      {
        "id": "github/gpt-6-astra",
        "label": "GPT-6 Astra"
      },
      {
        "id": "github/gpt-5.6-sol",
        "label": "GPT-5.6 Sol"
      },
      {
        "id": "github/gpt-5.6-terra",
        "label": "GPT-5.6 Terra"
      },
      {
        "id": "github/gpt-5.6-luna",
        "label": "GPT-5.6 Luna"
      },
      {
        "id": "github/gpt-5.5",
        "label": "GPT-5.5"
      },
      {
        "id": "github/claude-opus-4-8",
        "label": "Claude Opus 4.8"
      },
      {
        "id": "github/claude-fable-5-1",
        "label": "Claude Fable 5.1"
      },
      {
        "id": "github/claude-fable-5",
        "label": "Claude Fable 5"
      },
      {
        "id": "github/claude-sonnet-5",
        "label": "Claude Sonnet 5"
      },
      {
        "id": "github/claude-haiku-4-5",
        "label": "Claude Haiku 4.5"
      },
      {
        "id": "github/gemini-3.1-pro",
        "label": "Gemini 3.1 Pro"
      }
    ],
    "allowCustom": true,
    "defaultOwner": "cave"
  },
  "hermes": {
    "runtime": "hermes",
    "provider": "openai",
    "models": [
      {
        "id": "openai/gpt-5.6-sol",
        "label": "GPT-5.6 Sol"
      },
      {
        "id": "openai/gpt-6-astra",
        "label": "GPT-6 Astra"
      },
      {
        "id": "openai/gpt-5.6-terra",
        "label": "GPT-5.6 Terra"
      },
      {
        "id": "openai/gpt-5.6-luna",
        "label": "GPT-5.6 Luna"
      },
      {
        "id": "openai/gpt-5.5",
        "label": "GPT-5.5"
      },
      {
        "id": "openai/gpt-5.4",
        "label": "GPT-5.4"
      },
      {
        "id": "openai/gpt-5.4-mini",
        "label": "GPT-5.4 Mini"
      },
      {
        "id": "openai/gpt-5.3-codex-spark",
        "label": "GPT-5.3 Codex Spark"
      },
      {
        "id": "openai/codex-auto-review",
        "label": "Codex Auto Review"
      }
    ],
    "allowCustom": true,
    "defaultOwner": "runtime"
  },
  "grok": {
    "runtime": "grok",
    "provider": "xai",
    "models": [],
    "defaultModel": "grok-4.5",
    "allowCustom": true,
    "defaultOwner": "runtime"
  },
  "opencode": {
    "runtime": "opencode",
    "provider": null,
    "models": [],
    "defaultModel": "",
    "allowCustom": true,
    "defaultOwner": "runtime"
  },
  "openclaw": {
    "runtime": "openclaw",
    "provider": null,
    "models": [],
    "allowCustom": true,
    "defaultOwner": "runtime"
  }
};

export const GENERATED_MODEL_CONTEXT_WINDOWS: Record<string, number> =
  {
  "github/auto": 200000,
  "openai/gpt-5.6-sol": 1000000,
  "github/gpt-5.6-sol": 1000000,
  "openai/gpt-6-astra": 1000000,
  "github/gpt-6-astra": 1000000,
  "openai/gpt-5.6-terra": 1000000,
  "github/gpt-5.6-terra": 1000000,
  "openai/gpt-5.6-luna": 1000000,
  "github/gpt-5.6-luna": 1000000,
  "openai/gpt-5.5": 400000,
  "github/gpt-5.5": 400000,
  "openai/gpt-5.4": 400000,
  "openai/gpt-5.4-mini": 400000,
  "openai/gpt-5.3-codex-spark": 400000,
  "openai/gpt-5.1-codex-max": 400000,
  "openai/gpt-5.1-codex": 400000,
  "openai/gpt-5.1-codex-mini": 400000,
  "openai/gpt-5.1": 400000,
  "anthropic/claude-opus-5": 1000000,
  "github/claude-opus-5": 1000000,
  "anthropic/claude-opus-4-8": 1000000,
  "github/claude-opus-4-8": 1000000,
  "anthropic/claude-fable-5-1": 1000000,
  "github/claude-fable-5-1": 1000000,
  "anthropic/claude-fable-5": 1000000,
  "github/claude-fable-5": 1000000,
  "anthropic/claude-opus-4-7": 1000000,
  "anthropic/claude-opus-4-6": 1000000,
  "anthropic/claude-sonnet-5": 1000000,
  "github/claude-sonnet-5": 1000000,
  "anthropic/claude-sonnet-4-6": 1000000,
  "anthropic/claude-haiku-4-5": 200000,
  "github/claude-haiku-4-5": 200000,
  "github/gemini-3.1-pro": 1000000,
  "nous/hermes-4": 128000,
  "anthropic/opus": 1000000
};
