/**
 * Bundled font declarations — the runtime half of the typography feature.
 *
 * OpenCoven canonical type system (DESIGN.md §4):
 *   - Display (serif): EB Garamond
 *   - UI (sans):       Inter
 *   - Mono (code):     JetBrains Mono
 *
 * These three faces preload so a fresh profile renders the classic Coven
 * type system immediately. Everything else in the selectable catalog is
 * `preload: false`: its @font-face files download lazily and only for the
 * family whose cssVar is applied to rendered text.
 *
 * Every `--font-*` cssVar referenced by FONT_OPTIONS in
 * `src/lib/font-catalog.ts` is declared here, and all of their `.variable`
 * classes are concatenated into `fontVariables`, which the root layout
 * spreads onto <html>.
 *
 * The files are the vendored Google Fonts families (#5533), so builds never
 * reach the network for fonts. Each family's latin instance owns its cssVar,
 * preload flag and the fallback next/font/google chose; every other subset
 * Google serves is its own instance under the same font-family with Google's
 * unicode-range, so text in those scripts still gets the chosen font and
 * pages download only the subsets they use.
 */
import localFont from "next/font/local";

// GENERATED by scripts/vendor-fonts.mjs from src/assets/fonts/manifest.json.
// Edit FAMILIES in that script and run `node scripts/vendor-fonts.mjs --refresh`.
// next/font/local statically parses these calls at build time, so every
// argument must be an inline literal — no shared consts, spreads, or vars.

// ── Canonical Coven trio: preload (a fresh profile renders EB Garamond +
//    Inter + JetBrains Mono immediately, matching DESIGN.md §4). ──
export const ebGaramond = localFont({
  variable: "--font-eb-garamond",
  src: [
    { path: "../assets/fonts/eb-garamond-italic-400-800.woff2", weight: "400 800", style: "italic" },
    { path: "../assets/fonts/eb-garamond-normal-400-800.woff2", weight: "400 800", style: "normal" },
  ],
  adjustFontFallback: "Times New Roman",
  declarations: [
    { prop: "font-family", value: "'EB Garamond'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const ebGaramondCyrillicExt = localFont({
  src: [
    { path: "../assets/fonts/eb-garamond-cyrillic-ext-italic-400-800.woff2", weight: "400 800", style: "italic" },
    { path: "../assets/fonts/eb-garamond-cyrillic-ext-normal-400-800.woff2", weight: "400 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'EB Garamond'" },
    { prop: "unicode-range", value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F" },
  ],
});
const ebGaramondCyrillic = localFont({
  src: [
    { path: "../assets/fonts/eb-garamond-cyrillic-italic-400-800.woff2", weight: "400 800", style: "italic" },
    { path: "../assets/fonts/eb-garamond-cyrillic-normal-400-800.woff2", weight: "400 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'EB Garamond'" },
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});
const ebGaramondGreekExt = localFont({
  src: [
    { path: "../assets/fonts/eb-garamond-greek-ext-italic-400-800.woff2", weight: "400 800", style: "italic" },
    { path: "../assets/fonts/eb-garamond-greek-ext-normal-400-800.woff2", weight: "400 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'EB Garamond'" },
    { prop: "unicode-range", value: "U+1F00-1FFF" },
  ],
});
const ebGaramondGreek = localFont({
  src: [
    { path: "../assets/fonts/eb-garamond-greek-italic-400-800.woff2", weight: "400 800", style: "italic" },
    { path: "../assets/fonts/eb-garamond-greek-normal-400-800.woff2", weight: "400 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'EB Garamond'" },
    { prop: "unicode-range", value: "U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF" },
  ],
});
const ebGaramondVietnamese = localFont({
  src: [
    { path: "../assets/fonts/eb-garamond-vietnamese-italic-400-800.woff2", weight: "400 800", style: "italic" },
    { path: "../assets/fonts/eb-garamond-vietnamese-normal-400-800.woff2", weight: "400 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'EB Garamond'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const ebGaramondLatinExt = localFont({
  src: [
    { path: "../assets/fonts/eb-garamond-latin-ext-italic-400-800.woff2", weight: "400 800", style: "italic" },
    { path: "../assets/fonts/eb-garamond-latin-ext-normal-400-800.woff2", weight: "400 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'EB Garamond'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

export const inter = localFont({
  variable: "--font-inter",
  src: [
    { path: "../assets/fonts/inter-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Inter'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const interCyrillicExt = localFont({
  src: [
    { path: "../assets/fonts/inter-cyrillic-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Inter'" },
    { prop: "unicode-range", value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F" },
  ],
});
const interCyrillic = localFont({
  src: [
    { path: "../assets/fonts/inter-cyrillic-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Inter'" },
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});
const interGreekExt = localFont({
  src: [
    { path: "../assets/fonts/inter-greek-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Inter'" },
    { prop: "unicode-range", value: "U+1F00-1FFF" },
  ],
});
const interGreek = localFont({
  src: [
    { path: "../assets/fonts/inter-greek-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Inter'" },
    { prop: "unicode-range", value: "U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF" },
  ],
});
const interVietnamese = localFont({
  src: [
    { path: "../assets/fonts/inter-vietnamese-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Inter'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const interLatinExt = localFont({
  src: [
    { path: "../assets/fonts/inter-latin-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Inter'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

export const jetbrainsMono = localFont({
  variable: "--font-jetbrains-mono",
  src: [
    { path: "../assets/fonts/jetbrains-mono-normal-100-800.woff2", weight: "100 800", style: "normal" },
  ],
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'JetBrains Mono'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const jetbrainsMonoCyrillicExt = localFont({
  src: [
    { path: "../assets/fonts/jetbrains-mono-cyrillic-ext-normal-100-800.woff2", weight: "100 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'JetBrains Mono'" },
    { prop: "unicode-range", value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F" },
  ],
});
const jetbrainsMonoCyrillic = localFont({
  src: [
    { path: "../assets/fonts/jetbrains-mono-cyrillic-normal-100-800.woff2", weight: "100 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'JetBrains Mono'" },
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});
const jetbrainsMonoGreek = localFont({
  src: [
    { path: "../assets/fonts/jetbrains-mono-greek-normal-100-800.woff2", weight: "100 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'JetBrains Mono'" },
    { prop: "unicode-range", value: "U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF" },
  ],
});
const jetbrainsMonoVietnamese = localFont({
  src: [
    { path: "../assets/fonts/jetbrains-mono-vietnamese-normal-100-800.woff2", weight: "100 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'JetBrains Mono'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const jetbrainsMonoLatinExt = localFont({
  src: [
    { path: "../assets/fonts/jetbrains-mono-latin-ext-normal-100-800.woff2", weight: "100 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'JetBrains Mono'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

// ── Legacy defaults kept in the catalog as alternatives ──
// Geist / Geist Mono were the previous shipped defaults, and Fredoka the
// pre-v1.2 home headline. They stay declared so existing choices and custom
// themes that reference their cssVars keep working, but they don't preload.
export const geistSans = localFont({
  variable: "--font-geist-sans",
  src: [
    { path: "../assets/fonts/geist-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Geist'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const geistSansCyrillicExt = localFont({
  src: [
    { path: "../assets/fonts/geist-cyrillic-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Geist'" },
    { prop: "unicode-range", value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F" },
  ],
});
const geistSansCyrillic = localFont({
  src: [
    { path: "../assets/fonts/geist-cyrillic-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Geist'" },
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});
const geistSansVietnamese = localFont({
  src: [
    { path: "../assets/fonts/geist-vietnamese-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Geist'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const geistSansLatinExt = localFont({
  src: [
    { path: "../assets/fonts/geist-latin-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Geist'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

export const geistMono = localFont({
  variable: "--font-geist-mono",
  src: [
    { path: "../assets/fonts/geist-mono-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Geist Mono'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const geistMonoCyrillicExt = localFont({
  src: [
    { path: "../assets/fonts/geist-mono-cyrillic-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Geist Mono'" },
    { prop: "unicode-range", value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F" },
  ],
});
const geistMonoCyrillic = localFont({
  src: [
    { path: "../assets/fonts/geist-mono-cyrillic-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Geist Mono'" },
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});
const geistMonoSymbols2 = localFont({
  src: [
    { path: "../assets/fonts/geist-mono-symbols2-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Geist Mono'" },
    { prop: "unicode-range", value: "U+2000-2001, U+2004-2008, U+200A, U+23B8-23BD, U+2500-259F" },
  ],
});
const geistMonoVietnamese = localFont({
  src: [
    { path: "../assets/fonts/geist-mono-vietnamese-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Geist Mono'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const geistMonoLatinExt = localFont({
  src: [
    { path: "../assets/fonts/geist-mono-latin-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Geist Mono'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

export const fredoka = localFont({
  variable: "--font-fredoka",
  src: [
    { path: "../assets/fonts/fredoka-normal-300.woff2", weight: "300", style: "normal" },
    { path: "../assets/fonts/fredoka-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/fredoka-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/fredoka-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/fredoka-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Fredoka'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const fredokaHebrew = localFont({
  src: [
    { path: "../assets/fonts/fredoka-hebrew-normal-300.woff2", weight: "300", style: "normal" },
    { path: "../assets/fonts/fredoka-hebrew-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/fredoka-hebrew-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/fredoka-hebrew-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/fredoka-hebrew-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Fredoka'" },
    { prop: "unicode-range", value: "U+0307-0308, U+0590-05FF, U+200C-2010, U+20AA, U+25CC, U+FB1D-FB4F" },
  ],
});
const fredokaLatinExt = localFont({
  src: [
    { path: "../assets/fonts/fredoka-latin-ext-normal-300.woff2", weight: "300", style: "normal" },
    { path: "../assets/fonts/fredoka-latin-ext-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/fredoka-latin-ext-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/fredoka-latin-ext-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/fredoka-latin-ext-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Fredoka'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

// ── Additional Coven serifs (preload: false, selectable via catalog) ──
export const instrumentSerif = localFont({
  variable: "--font-instrument-serif",
  src: [
    { path: "../assets/fonts/instrument-serif-italic-400.woff2", weight: "400", style: "italic" },
    { path: "../assets/fonts/instrument-serif-normal-400.woff2", weight: "400", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Times New Roman",
  declarations: [
    { prop: "font-family", value: "'Instrument Serif'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const instrumentSerifLatinExt = localFont({
  src: [
    { path: "../assets/fonts/instrument-serif-latin-ext-italic-400.woff2", weight: "400", style: "italic" },
    { path: "../assets/fonts/instrument-serif-latin-ext-normal-400.woff2", weight: "400", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Instrument Serif'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

export const fraunces = localFont({
  variable: "--font-fraunces",
  src: [
    { path: "../assets/fonts/fraunces-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Times New Roman",
  declarations: [
    { prop: "font-family", value: "'Fraunces'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const frauncesVietnamese = localFont({
  src: [
    { path: "../assets/fonts/fraunces-vietnamese-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Fraunces'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const frauncesLatinExt = localFont({
  src: [
    { path: "../assets/fonts/fraunces-latin-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Fraunces'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

// ── Sans catalog (preload: false) ──
const roboto = localFont({
  variable: "--font-roboto",
  src: [
    { path: "../assets/fonts/roboto-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Roboto'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const robotoCyrillicExt = localFont({
  src: [
    { path: "../assets/fonts/roboto-cyrillic-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Roboto'" },
    { prop: "unicode-range", value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F" },
  ],
});
const robotoCyrillic = localFont({
  src: [
    { path: "../assets/fonts/roboto-cyrillic-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Roboto'" },
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});
const robotoGreekExt = localFont({
  src: [
    { path: "../assets/fonts/roboto-greek-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Roboto'" },
    { prop: "unicode-range", value: "U+1F00-1FFF" },
  ],
});
const robotoGreek = localFont({
  src: [
    { path: "../assets/fonts/roboto-greek-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Roboto'" },
    { prop: "unicode-range", value: "U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF" },
  ],
});
const robotoMath = localFont({
  src: [
    { path: "../assets/fonts/roboto-math-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Roboto'" },
    { prop: "unicode-range", value: "U+0302-0303, U+0305, U+0307-0308, U+0310, U+0312, U+0315, U+031A, U+0326-0327, U+032C, U+032F-0330, U+0332-0333, U+0338, U+033A, U+0346, U+034D, U+0391-03A1, U+03A3-03A9, U+03B1-03C9, U+03D1, U+03D5-03D6, U+03F0-03F1, U+03F4-03F5, U+2016-2017, U+2034-2038, U+203C, U+2040, U+2043, U+2047, U+2050, U+2057, U+205F, U+2070-2071, U+2074-208E, U+2090-209C, U+20D0-20DC, U+20E1, U+20E5-20EF, U+2100-2112, U+2114-2115, U+2117-2121, U+2123-214F, U+2190, U+2192, U+2194-21AE, U+21B0-21E5, U+21F1-21F2, U+21F4-2211, U+2213-2214, U+2216-22FF, U+2308-230B, U+2310, U+2319, U+231C-2321, U+2336-237A, U+237C, U+2395, U+239B-23B7, U+23D0, U+23DC-23E1, U+2474-2475, U+25AF, U+25B3, U+25B7, U+25BD, U+25C1, U+25CA, U+25CC, U+25FB, U+266D-266F, U+27C0-27FF, U+2900-2AFF, U+2B0E-2B11, U+2B30-2B4C, U+2BFE, U+3030, U+FF5B, U+FF5D, U+1D400-1D7FF, U+1EE00-1EEFF" },
  ],
});
const robotoSymbols = localFont({
  src: [
    { path: "../assets/fonts/roboto-symbols-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Roboto'" },
    { prop: "unicode-range", value: "U+0001-000C, U+000E-001F, U+007F-009F, U+20DD-20E0, U+20E2-20E4, U+2150-218F, U+2190, U+2192, U+2194-2199, U+21AF, U+21E6-21F0, U+21F3, U+2218-2219, U+2299, U+22C4-22C6, U+2300-243F, U+2440-244A, U+2460-24FF, U+25A0-27BF, U+2800-28FF, U+2921-2922, U+2981, U+29BF, U+29EB, U+2B00-2BFF, U+4DC0-4DFF, U+FFF9-FFFB, U+10140-1018E, U+10190-1019C, U+101A0, U+101D0-101FD, U+102E0-102FB, U+10E60-10E7E, U+1D2C0-1D2D3, U+1D2E0-1D37F, U+1F000-1F0FF, U+1F100-1F1AD, U+1F1E6-1F1FF, U+1F30D-1F30F, U+1F315, U+1F31C, U+1F31E, U+1F320-1F32C, U+1F336, U+1F378, U+1F37D, U+1F382, U+1F393-1F39F, U+1F3A7-1F3A8, U+1F3AC-1F3AF, U+1F3C2, U+1F3C4-1F3C6, U+1F3CA-1F3CE, U+1F3D4-1F3E0, U+1F3ED, U+1F3F1-1F3F3, U+1F3F5-1F3F7, U+1F408, U+1F415, U+1F41F, U+1F426, U+1F43F, U+1F441-1F442, U+1F444, U+1F446-1F449, U+1F44C-1F44E, U+1F453, U+1F46A, U+1F47D, U+1F4A3, U+1F4B0, U+1F4B3, U+1F4B9, U+1F4BB, U+1F4BF, U+1F4C8-1F4CB, U+1F4D6, U+1F4DA, U+1F4DF, U+1F4E3-1F4E6, U+1F4EA-1F4ED, U+1F4F7, U+1F4F9-1F4FB, U+1F4FD-1F4FE, U+1F503, U+1F507-1F50B, U+1F50D, U+1F512-1F513, U+1F53E-1F54A, U+1F54F-1F5FA, U+1F610, U+1F650-1F67F, U+1F687, U+1F68D, U+1F691, U+1F694, U+1F698, U+1F6AD, U+1F6B2, U+1F6B9-1F6BA, U+1F6BC, U+1F6C6-1F6CF, U+1F6D3-1F6D7, U+1F6E0-1F6EA, U+1F6F0-1F6F3, U+1F6F7-1F6FC, U+1F700-1F7FF, U+1F800-1F80B, U+1F810-1F847, U+1F850-1F859, U+1F860-1F887, U+1F890-1F8AD, U+1F8B0-1F8BB, U+1F8C0-1F8C1, U+1F900-1F90B, U+1F93B, U+1F946, U+1F984, U+1F996, U+1F9E9, U+1FA00-1FA6F, U+1FA70-1FA7C, U+1FA80-1FA89, U+1FA8F-1FAC6, U+1FACE-1FADC, U+1FADF-1FAE9, U+1FAF0-1FAF8, U+1FB00-1FBFF" },
  ],
});
const robotoVietnamese = localFont({
  src: [
    { path: "../assets/fonts/roboto-vietnamese-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Roboto'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const robotoLatinExt = localFont({
  src: [
    { path: "../assets/fonts/roboto-latin-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Roboto'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

const openSans = localFont({
  variable: "--font-open-sans",
  src: [
    { path: "../assets/fonts/open-sans-normal-300-800.woff2", weight: "300 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Open Sans'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const openSansCyrillicExt = localFont({
  src: [
    { path: "../assets/fonts/open-sans-cyrillic-ext-normal-300-800.woff2", weight: "300 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Open Sans'" },
    { prop: "unicode-range", value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F" },
  ],
});
const openSansCyrillic = localFont({
  src: [
    { path: "../assets/fonts/open-sans-cyrillic-normal-300-800.woff2", weight: "300 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Open Sans'" },
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});
const openSansGreekExt = localFont({
  src: [
    { path: "../assets/fonts/open-sans-greek-ext-normal-300-800.woff2", weight: "300 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Open Sans'" },
    { prop: "unicode-range", value: "U+1F00-1FFF" },
  ],
});
const openSansGreek = localFont({
  src: [
    { path: "../assets/fonts/open-sans-greek-normal-300-800.woff2", weight: "300 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Open Sans'" },
    { prop: "unicode-range", value: "U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF" },
  ],
});
const openSansHebrew = localFont({
  src: [
    { path: "../assets/fonts/open-sans-hebrew-normal-300-800.woff2", weight: "300 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Open Sans'" },
    { prop: "unicode-range", value: "U+0307-0308, U+0590-05FF, U+200C-2010, U+20AA, U+25CC, U+FB1D-FB4F" },
  ],
});
const openSansMath = localFont({
  src: [
    { path: "../assets/fonts/open-sans-math-normal-300-800.woff2", weight: "300 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Open Sans'" },
    { prop: "unicode-range", value: "U+0302-0303, U+0305, U+0307-0308, U+0310, U+0312, U+0315, U+031A, U+0326-0327, U+032C, U+032F-0330, U+0332-0333, U+0338, U+033A, U+0346, U+034D, U+0391-03A1, U+03A3-03A9, U+03B1-03C9, U+03D1, U+03D5-03D6, U+03F0-03F1, U+03F4-03F5, U+2016-2017, U+2034-2038, U+203C, U+2040, U+2043, U+2047, U+2050, U+2057, U+205F, U+2070-2071, U+2074-208E, U+2090-209C, U+20D0-20DC, U+20E1, U+20E5-20EF, U+2100-2112, U+2114-2115, U+2117-2121, U+2123-214F, U+2190, U+2192, U+2194-21AE, U+21B0-21E5, U+21F1-21F2, U+21F4-2211, U+2213-2214, U+2216-22FF, U+2308-230B, U+2310, U+2319, U+231C-2321, U+2336-237A, U+237C, U+2395, U+239B-23B7, U+23D0, U+23DC-23E1, U+2474-2475, U+25AF, U+25B3, U+25B7, U+25BD, U+25C1, U+25CA, U+25CC, U+25FB, U+266D-266F, U+27C0-27FF, U+2900-2AFF, U+2B0E-2B11, U+2B30-2B4C, U+2BFE, U+3030, U+FF5B, U+FF5D, U+1D400-1D7FF, U+1EE00-1EEFF" },
  ],
});
const openSansSymbols = localFont({
  src: [
    { path: "../assets/fonts/open-sans-symbols-normal-300-800.woff2", weight: "300 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Open Sans'" },
    { prop: "unicode-range", value: "U+0001-000C, U+000E-001F, U+007F-009F, U+20DD-20E0, U+20E2-20E4, U+2150-218F, U+2190, U+2192, U+2194-2199, U+21AF, U+21E6-21F0, U+21F3, U+2218-2219, U+2299, U+22C4-22C6, U+2300-243F, U+2440-244A, U+2460-24FF, U+25A0-27BF, U+2800-28FF, U+2921-2922, U+2981, U+29BF, U+29EB, U+2B00-2BFF, U+4DC0-4DFF, U+FFF9-FFFB, U+10140-1018E, U+10190-1019C, U+101A0, U+101D0-101FD, U+102E0-102FB, U+10E60-10E7E, U+1D2C0-1D2D3, U+1D2E0-1D37F, U+1F000-1F0FF, U+1F100-1F1AD, U+1F1E6-1F1FF, U+1F30D-1F30F, U+1F315, U+1F31C, U+1F31E, U+1F320-1F32C, U+1F336, U+1F378, U+1F37D, U+1F382, U+1F393-1F39F, U+1F3A7-1F3A8, U+1F3AC-1F3AF, U+1F3C2, U+1F3C4-1F3C6, U+1F3CA-1F3CE, U+1F3D4-1F3E0, U+1F3ED, U+1F3F1-1F3F3, U+1F3F5-1F3F7, U+1F408, U+1F415, U+1F41F, U+1F426, U+1F43F, U+1F441-1F442, U+1F444, U+1F446-1F449, U+1F44C-1F44E, U+1F453, U+1F46A, U+1F47D, U+1F4A3, U+1F4B0, U+1F4B3, U+1F4B9, U+1F4BB, U+1F4BF, U+1F4C8-1F4CB, U+1F4D6, U+1F4DA, U+1F4DF, U+1F4E3-1F4E6, U+1F4EA-1F4ED, U+1F4F7, U+1F4F9-1F4FB, U+1F4FD-1F4FE, U+1F503, U+1F507-1F50B, U+1F50D, U+1F512-1F513, U+1F53E-1F54A, U+1F54F-1F5FA, U+1F610, U+1F650-1F67F, U+1F687, U+1F68D, U+1F691, U+1F694, U+1F698, U+1F6AD, U+1F6B2, U+1F6B9-1F6BA, U+1F6BC, U+1F6C6-1F6CF, U+1F6D3-1F6D7, U+1F6E0-1F6EA, U+1F6F0-1F6F3, U+1F6F7-1F6FC, U+1F700-1F7FF, U+1F800-1F80B, U+1F810-1F847, U+1F850-1F859, U+1F860-1F887, U+1F890-1F8AD, U+1F8B0-1F8BB, U+1F8C0-1F8C1, U+1F900-1F90B, U+1F93B, U+1F946, U+1F984, U+1F996, U+1F9E9, U+1FA00-1FA6F, U+1FA70-1FA7C, U+1FA80-1FA89, U+1FA8F-1FAC6, U+1FACE-1FADC, U+1FADF-1FAE9, U+1FAF0-1FAF8, U+1FB00-1FBFF" },
  ],
});
const openSansVietnamese = localFont({
  src: [
    { path: "../assets/fonts/open-sans-vietnamese-normal-300-800.woff2", weight: "300 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Open Sans'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const openSansLatinExt = localFont({
  src: [
    { path: "../assets/fonts/open-sans-latin-ext-normal-300-800.woff2", weight: "300 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Open Sans'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

const lato = localFont({
  variable: "--font-lato",
  src: [
    { path: "../assets/fonts/lato-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/lato-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Lato'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const latoLatinExt = localFont({
  src: [
    { path: "../assets/fonts/lato-latin-ext-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/lato-latin-ext-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Lato'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

const sourceSans3 = localFont({
  variable: "--font-source-sans-3",
  src: [
    { path: "../assets/fonts/source-sans-3-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Source Sans 3'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const sourceSans3CyrillicExt = localFont({
  src: [
    { path: "../assets/fonts/source-sans-3-cyrillic-ext-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Source Sans 3'" },
    { prop: "unicode-range", value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F" },
  ],
});
const sourceSans3Cyrillic = localFont({
  src: [
    { path: "../assets/fonts/source-sans-3-cyrillic-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Source Sans 3'" },
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});
const sourceSans3GreekExt = localFont({
  src: [
    { path: "../assets/fonts/source-sans-3-greek-ext-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Source Sans 3'" },
    { prop: "unicode-range", value: "U+1F00-1FFF" },
  ],
});
const sourceSans3Greek = localFont({
  src: [
    { path: "../assets/fonts/source-sans-3-greek-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Source Sans 3'" },
    { prop: "unicode-range", value: "U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF" },
  ],
});
const sourceSans3Vietnamese = localFont({
  src: [
    { path: "../assets/fonts/source-sans-3-vietnamese-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Source Sans 3'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const sourceSans3LatinExt = localFont({
  src: [
    { path: "../assets/fonts/source-sans-3-latin-ext-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Source Sans 3'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

const notoSans = localFont({
  variable: "--font-noto-sans",
  src: [
    { path: "../assets/fonts/noto-sans-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Noto Sans'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const notoSansCyrillicExt = localFont({
  src: [
    { path: "../assets/fonts/noto-sans-cyrillic-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Noto Sans'" },
    { prop: "unicode-range", value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F" },
  ],
});
const notoSansCyrillic = localFont({
  src: [
    { path: "../assets/fonts/noto-sans-cyrillic-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Noto Sans'" },
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});
const notoSansDevanagari = localFont({
  src: [
    { path: "../assets/fonts/noto-sans-devanagari-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Noto Sans'" },
    { prop: "unicode-range", value: "U+0900-097F, U+1CD0-1CF9, U+200C-200D, U+20A8, U+20B9, U+20F0, U+25CC, U+A830-A839, U+A8E0-A8FF, U+11B00-11B09" },
  ],
});
const notoSansGreekExt = localFont({
  src: [
    { path: "../assets/fonts/noto-sans-greek-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Noto Sans'" },
    { prop: "unicode-range", value: "U+1F00-1FFF" },
  ],
});
const notoSansGreek = localFont({
  src: [
    { path: "../assets/fonts/noto-sans-greek-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Noto Sans'" },
    { prop: "unicode-range", value: "U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF" },
  ],
});
const notoSansVietnamese = localFont({
  src: [
    { path: "../assets/fonts/noto-sans-vietnamese-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Noto Sans'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const notoSansLatinExt = localFont({
  src: [
    { path: "../assets/fonts/noto-sans-latin-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Noto Sans'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

const ibmPlexSans = localFont({
  variable: "--font-ibm-plex-sans",
  src: [
    { path: "../assets/fonts/ibm-plex-sans-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'IBM Plex Sans'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const ibmPlexSansCyrillicExt = localFont({
  src: [
    { path: "../assets/fonts/ibm-plex-sans-cyrillic-ext-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-cyrillic-ext-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-cyrillic-ext-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-cyrillic-ext-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'IBM Plex Sans'" },
    { prop: "unicode-range", value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F" },
  ],
});
const ibmPlexSansCyrillic = localFont({
  src: [
    { path: "../assets/fonts/ibm-plex-sans-cyrillic-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-cyrillic-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-cyrillic-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-cyrillic-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'IBM Plex Sans'" },
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});
const ibmPlexSansGreek = localFont({
  src: [
    { path: "../assets/fonts/ibm-plex-sans-greek-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-greek-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-greek-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-greek-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'IBM Plex Sans'" },
    { prop: "unicode-range", value: "U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF" },
  ],
});
const ibmPlexSansVietnamese = localFont({
  src: [
    { path: "../assets/fonts/ibm-plex-sans-vietnamese-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-vietnamese-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-vietnamese-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-vietnamese-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'IBM Plex Sans'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const ibmPlexSansLatinExt = localFont({
  src: [
    { path: "../assets/fonts/ibm-plex-sans-latin-ext-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-latin-ext-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-latin-ext-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-latin-ext-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'IBM Plex Sans'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

const workSans = localFont({
  variable: "--font-work-sans",
  src: [
    { path: "../assets/fonts/work-sans-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Work Sans'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const workSansVietnamese = localFont({
  src: [
    { path: "../assets/fonts/work-sans-vietnamese-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Work Sans'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const workSansLatinExt = localFont({
  src: [
    { path: "../assets/fonts/work-sans-latin-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Work Sans'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

const dmSans = localFont({
  variable: "--font-dm-sans",
  src: [
    { path: "../assets/fonts/dm-sans-normal-100-1000.woff2", weight: "100 1000", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'DM Sans'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const dmSansLatinExt = localFont({
  src: [
    { path: "../assets/fonts/dm-sans-latin-ext-normal-100-1000.woff2", weight: "100 1000", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'DM Sans'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

const manrope = localFont({
  variable: "--font-manrope",
  src: [
    { path: "../assets/fonts/manrope-normal-200-800.woff2", weight: "200 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Manrope'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const manropeCyrillicExt = localFont({
  src: [
    { path: "../assets/fonts/manrope-cyrillic-ext-normal-200-800.woff2", weight: "200 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Manrope'" },
    { prop: "unicode-range", value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F" },
  ],
});
const manropeCyrillic = localFont({
  src: [
    { path: "../assets/fonts/manrope-cyrillic-normal-200-800.woff2", weight: "200 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Manrope'" },
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});
const manropeGreek = localFont({
  src: [
    { path: "../assets/fonts/manrope-greek-normal-200-800.woff2", weight: "200 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Manrope'" },
    { prop: "unicode-range", value: "U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF" },
  ],
});
const manropeVietnamese = localFont({
  src: [
    { path: "../assets/fonts/manrope-vietnamese-normal-200-800.woff2", weight: "200 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Manrope'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const manropeLatinExt = localFont({
  src: [
    { path: "../assets/fonts/manrope-latin-ext-normal-200-800.woff2", weight: "200 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Manrope'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

const figtree = localFont({
  variable: "--font-figtree",
  src: [
    { path: "../assets/fonts/figtree-normal-300-900.woff2", weight: "300 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Figtree'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const figtreeLatinExt = localFont({
  src: [
    { path: "../assets/fonts/figtree-latin-ext-normal-300-900.woff2", weight: "300 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Figtree'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

const publicSans = localFont({
  variable: "--font-public-sans",
  src: [
    { path: "../assets/fonts/public-sans-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Public Sans'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const publicSansVietnamese = localFont({
  src: [
    { path: "../assets/fonts/public-sans-vietnamese-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Public Sans'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const publicSansLatinExt = localFont({
  src: [
    { path: "../assets/fonts/public-sans-latin-ext-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Public Sans'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

// ── Mono catalog (preload: false) ──
const firaCode = localFont({
  variable: "--font-fira-code",
  src: [
    { path: "../assets/fonts/fira-code-normal-300-700.woff2", weight: "300 700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Fira Code'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const firaCodeCyrillicExt = localFont({
  src: [
    { path: "../assets/fonts/fira-code-cyrillic-ext-normal-300-700.woff2", weight: "300 700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Fira Code'" },
    { prop: "unicode-range", value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F" },
  ],
});
const firaCodeCyrillic = localFont({
  src: [
    { path: "../assets/fonts/fira-code-cyrillic-normal-300-700.woff2", weight: "300 700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Fira Code'" },
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});
const firaCodeGreekExt = localFont({
  src: [
    { path: "../assets/fonts/fira-code-greek-ext-normal-300-700.woff2", weight: "300 700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Fira Code'" },
    { prop: "unicode-range", value: "U+1F00-1FFF" },
  ],
});
const firaCodeGreek = localFont({
  src: [
    { path: "../assets/fonts/fira-code-greek-normal-300-700.woff2", weight: "300 700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Fira Code'" },
    { prop: "unicode-range", value: "U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF" },
  ],
});
const firaCodeSymbols2 = localFont({
  src: [
    { path: "../assets/fonts/fira-code-symbols2-normal-300-700.woff2", weight: "300 700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Fira Code'" },
    { prop: "unicode-range", value: "U+2000-2001, U+2004-2008, U+200A, U+23B8-23BD, U+2500-259F" },
  ],
});
const firaCodeLatinExt = localFont({
  src: [
    { path: "../assets/fonts/fira-code-latin-ext-normal-300-700.woff2", weight: "300 700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Fira Code'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

const sourceCodePro = localFont({
  variable: "--font-source-code-pro",
  src: [
    { path: "../assets/fonts/source-code-pro-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Source Code Pro'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const sourceCodeProCyrillicExt = localFont({
  src: [
    { path: "../assets/fonts/source-code-pro-cyrillic-ext-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Source Code Pro'" },
    { prop: "unicode-range", value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F" },
  ],
});
const sourceCodeProCyrillic = localFont({
  src: [
    { path: "../assets/fonts/source-code-pro-cyrillic-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Source Code Pro'" },
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});
const sourceCodeProGreekExt = localFont({
  src: [
    { path: "../assets/fonts/source-code-pro-greek-ext-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Source Code Pro'" },
    { prop: "unicode-range", value: "U+1F00-1FFF" },
  ],
});
const sourceCodeProGreek = localFont({
  src: [
    { path: "../assets/fonts/source-code-pro-greek-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Source Code Pro'" },
    { prop: "unicode-range", value: "U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF" },
  ],
});
const sourceCodeProVietnamese = localFont({
  src: [
    { path: "../assets/fonts/source-code-pro-vietnamese-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Source Code Pro'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const sourceCodeProLatinExt = localFont({
  src: [
    { path: "../assets/fonts/source-code-pro-latin-ext-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Source Code Pro'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

const ibmPlexMono = localFont({
  variable: "--font-ibm-plex-mono",
  src: [
    { path: "../assets/fonts/ibm-plex-mono-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'IBM Plex Mono'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const ibmPlexMonoCyrillicExt = localFont({
  src: [
    { path: "../assets/fonts/ibm-plex-mono-cyrillic-ext-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-cyrillic-ext-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-cyrillic-ext-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-cyrillic-ext-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'IBM Plex Mono'" },
    { prop: "unicode-range", value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F" },
  ],
});
const ibmPlexMonoCyrillic = localFont({
  src: [
    { path: "../assets/fonts/ibm-plex-mono-cyrillic-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-cyrillic-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-cyrillic-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-cyrillic-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'IBM Plex Mono'" },
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});
const ibmPlexMonoVietnamese = localFont({
  src: [
    { path: "../assets/fonts/ibm-plex-mono-vietnamese-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-vietnamese-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-vietnamese-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-vietnamese-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'IBM Plex Mono'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const ibmPlexMonoLatinExt = localFont({
  src: [
    { path: "../assets/fonts/ibm-plex-mono-latin-ext-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-latin-ext-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-latin-ext-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-latin-ext-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'IBM Plex Mono'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

const robotoMono = localFont({
  variable: "--font-roboto-mono",
  src: [
    { path: "../assets/fonts/roboto-mono-normal-100-700.woff2", weight: "100 700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Roboto Mono'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const robotoMonoCyrillicExt = localFont({
  src: [
    { path: "../assets/fonts/roboto-mono-cyrillic-ext-normal-100-700.woff2", weight: "100 700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Roboto Mono'" },
    { prop: "unicode-range", value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F" },
  ],
});
const robotoMonoCyrillic = localFont({
  src: [
    { path: "../assets/fonts/roboto-mono-cyrillic-normal-100-700.woff2", weight: "100 700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Roboto Mono'" },
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});
const robotoMonoGreek = localFont({
  src: [
    { path: "../assets/fonts/roboto-mono-greek-normal-100-700.woff2", weight: "100 700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Roboto Mono'" },
    { prop: "unicode-range", value: "U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF" },
  ],
});
const robotoMonoVietnamese = localFont({
  src: [
    { path: "../assets/fonts/roboto-mono-vietnamese-normal-100-700.woff2", weight: "100 700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Roboto Mono'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const robotoMonoLatinExt = localFont({
  src: [
    { path: "../assets/fonts/roboto-mono-latin-ext-normal-100-700.woff2", weight: "100 700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Roboto Mono'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

const spaceMono = localFont({
  variable: "--font-space-mono",
  src: [
    { path: "../assets/fonts/space-mono-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/space-mono-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Space Mono'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const spaceMonoVietnamese = localFont({
  src: [
    { path: "../assets/fonts/space-mono-vietnamese-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/space-mono-vietnamese-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Space Mono'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const spaceMonoLatinExt = localFont({
  src: [
    { path: "../assets/fonts/space-mono-latin-ext-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/space-mono-latin-ext-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Space Mono'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

const inconsolata = localFont({
  variable: "--font-inconsolata",
  src: [
    { path: "../assets/fonts/inconsolata-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [
    { prop: "font-family", value: "'Inconsolata'" },
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});
const inconsolataVietnamese = localFont({
  src: [
    { path: "../assets/fonts/inconsolata-vietnamese-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Inconsolata'" },
    { prop: "unicode-range", value: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB" },
  ],
});
const inconsolataLatinExt = localFont({
  src: [
    { path: "../assets/fonts/inconsolata-latin-ext-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "font-family", value: "'Inconsolata'" },
    { prop: "unicode-range", value: "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF" },
  ],
});

/** Every declared font instance — order is irrelevant; the layout just
 *  needs all `.variable` classes on the same element. */
const ALL_FONTS = [
  ebGaramond,
  inter,
  jetbrainsMono,
  geistSans,
  geistMono,
  fredoka,
  instrumentSerif,
  fraunces,
  roboto,
  openSans,
  lato,
  sourceSans3,
  notoSans,
  ibmPlexSans,
  workSans,
  dmSans,
  manrope,
  figtree,
  publicSans,
  firaCode,
  sourceCodePro,
  ibmPlexMono,
  robotoMono,
  spaceMono,
  inconsolata,
];

/** Space-joined `.variable` classes for the root <html> element. */
export const fontVariables = ALL_FONTS.map((f) => f.variable).join(" ");

/** Non-latin subsets. Referenced so their @font-face rules always ship. */
export const vendoredSubsetFaces = [
  ebGaramondCyrillicExt,
  ebGaramondCyrillic,
  ebGaramondGreekExt,
  ebGaramondGreek,
  ebGaramondVietnamese,
  ebGaramondLatinExt,
  interCyrillicExt,
  interCyrillic,
  interGreekExt,
  interGreek,
  interVietnamese,
  interLatinExt,
  jetbrainsMonoCyrillicExt,
  jetbrainsMonoCyrillic,
  jetbrainsMonoGreek,
  jetbrainsMonoVietnamese,
  jetbrainsMonoLatinExt,
  geistSansCyrillicExt,
  geistSansCyrillic,
  geistSansVietnamese,
  geistSansLatinExt,
  geistMonoCyrillicExt,
  geistMonoCyrillic,
  geistMonoSymbols2,
  geistMonoVietnamese,
  geistMonoLatinExt,
  fredokaHebrew,
  fredokaLatinExt,
  instrumentSerifLatinExt,
  frauncesVietnamese,
  frauncesLatinExt,
  robotoCyrillicExt,
  robotoCyrillic,
  robotoGreekExt,
  robotoGreek,
  robotoMath,
  robotoSymbols,
  robotoVietnamese,
  robotoLatinExt,
  openSansCyrillicExt,
  openSansCyrillic,
  openSansGreekExt,
  openSansGreek,
  openSansHebrew,
  openSansMath,
  openSansSymbols,
  openSansVietnamese,
  openSansLatinExt,
  latoLatinExt,
  sourceSans3CyrillicExt,
  sourceSans3Cyrillic,
  sourceSans3GreekExt,
  sourceSans3Greek,
  sourceSans3Vietnamese,
  sourceSans3LatinExt,
  notoSansCyrillicExt,
  notoSansCyrillic,
  notoSansDevanagari,
  notoSansGreekExt,
  notoSansGreek,
  notoSansVietnamese,
  notoSansLatinExt,
  ibmPlexSansCyrillicExt,
  ibmPlexSansCyrillic,
  ibmPlexSansGreek,
  ibmPlexSansVietnamese,
  ibmPlexSansLatinExt,
  workSansVietnamese,
  workSansLatinExt,
  dmSansLatinExt,
  manropeCyrillicExt,
  manropeCyrillic,
  manropeGreek,
  manropeVietnamese,
  manropeLatinExt,
  figtreeLatinExt,
  publicSansVietnamese,
  publicSansLatinExt,
  firaCodeCyrillicExt,
  firaCodeCyrillic,
  firaCodeGreekExt,
  firaCodeGreek,
  firaCodeSymbols2,
  firaCodeLatinExt,
  sourceCodeProCyrillicExt,
  sourceCodeProCyrillic,
  sourceCodeProGreekExt,
  sourceCodeProGreek,
  sourceCodeProVietnamese,
  sourceCodeProLatinExt,
  ibmPlexMonoCyrillicExt,
  ibmPlexMonoCyrillic,
  ibmPlexMonoVietnamese,
  ibmPlexMonoLatinExt,
  robotoMonoCyrillicExt,
  robotoMonoCyrillic,
  robotoMonoGreek,
  robotoMonoVietnamese,
  robotoMonoLatinExt,
  spaceMonoVietnamese,
  spaceMonoLatinExt,
  inconsolataVietnamese,
  inconsolataLatinExt,
];
