/**
 * Bundled font declarations — the runtime half of the typography feature.
 *
 * OpenCoven canonical type system (DESIGN.md §4):
 *   - Display (serif): EB Garamond
 *   - UI (sans):       Inter
 *   - Mono (code):     JetBrains Mono
 *
 * These three faces preload so a fresh profile renders the classic Coven
 * type system immediately. Everything else in the selectable catalog is
 * `preload: false`: its @font-face files download lazily and only for the
 * family whose cssVar is applied to rendered text.
 *
 * Every `--font-*` cssVar referenced by FONT_OPTIONS in
 * `src/lib/font-catalog.ts` is declared here, and all of their `.variable`
 * classes are concatenated into `fontVariables`, which the root layout
 * spreads onto <html>.
 *
 * The files are vendored latin subsets of the Google Fonts families (#5533),
 * so builds never reach the network for fonts. Each family keeps the fallback
 * font next/font/google chose for it and Google's latin unicode-range.
 */
import localFont from "next/font/local";

// GENERATED by scripts/vendor-fonts.mjs from src/assets/fonts/manifest.json.
// Edit FAMILIES in that script and run `node scripts/vendor-fonts.mjs --refresh`.
// next/font/local statically parses these calls at build time, so every
// argument must be an inline literal — no shared consts, spreads, or vars.

// ── Canonical Coven trio: preload (a fresh profile renders EB Garamond +
//    Inter + JetBrains Mono immediately, matching DESIGN.md §4). ──
export const ebGaramond = localFont({
  variable: "--font-eb-garamond",
  src: [
    { path: "../assets/fonts/eb-garamond-italic-400-800.woff2", weight: "400 800", style: "italic" },
    { path: "../assets/fonts/eb-garamond-normal-400-800.woff2", weight: "400 800", style: "normal" },
  ],
  adjustFontFallback: "Times New Roman",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

export const inter = localFont({
  variable: "--font-inter",
  src: [
    { path: "../assets/fonts/inter-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

export const jetbrainsMono = localFont({
  variable: "--font-jetbrains-mono",
  src: [
    { path: "../assets/fonts/jetbrains-mono-normal-100-800.woff2", weight: "100 800", style: "normal" },
  ],
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

// ── Legacy defaults kept in the catalog as alternatives ──
// Geist / Geist Mono were the previous shipped defaults, and Fredoka the
// pre-v1.2 home headline. They stay declared so existing choices and custom
// themes that reference their cssVars keep working, but they don't preload.
export const geistSans = localFont({
  variable: "--font-geist-sans",
  src: [
    { path: "../assets/fonts/geist-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

export const geistMono = localFont({
  variable: "--font-geist-mono",
  src: [
    { path: "../assets/fonts/geist-mono-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

export const fredoka = localFont({
  variable: "--font-fredoka",
  src: [
    { path: "../assets/fonts/fredoka-normal-300.woff2", weight: "300", style: "normal" },
    { path: "../assets/fonts/fredoka-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/fredoka-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/fredoka-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/fredoka-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

// ── Additional Coven serifs (preload: false, selectable via catalog) ──
export const instrumentSerif = localFont({
  variable: "--font-instrument-serif",
  src: [
    { path: "../assets/fonts/instrument-serif-italic-400.woff2", weight: "400", style: "italic" },
    { path: "../assets/fonts/instrument-serif-normal-400.woff2", weight: "400", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Times New Roman",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

export const fraunces = localFont({
  variable: "--font-fraunces",
  src: [
    { path: "../assets/fonts/fraunces-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Times New Roman",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

// ── Sans catalog (preload: false) ──
const roboto = localFont({
  variable: "--font-roboto",
  src: [
    { path: "../assets/fonts/roboto-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

const openSans = localFont({
  variable: "--font-open-sans",
  src: [
    { path: "../assets/fonts/open-sans-normal-300-800.woff2", weight: "300 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

const lato = localFont({
  variable: "--font-lato",
  src: [
    { path: "../assets/fonts/lato-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/lato-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

const sourceSans3 = localFont({
  variable: "--font-source-sans-3",
  src: [
    { path: "../assets/fonts/source-sans-3-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

const notoSans = localFont({
  variable: "--font-noto-sans",
  src: [
    { path: "../assets/fonts/noto-sans-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

const ibmPlexSans = localFont({
  variable: "--font-ibm-plex-sans",
  src: [
    { path: "../assets/fonts/ibm-plex-sans-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/ibm-plex-sans-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

const workSans = localFont({
  variable: "--font-work-sans",
  src: [
    { path: "../assets/fonts/work-sans-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

const dmSans = localFont({
  variable: "--font-dm-sans",
  src: [
    { path: "../assets/fonts/dm-sans-normal-100-1000.woff2", weight: "100 1000", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

const manrope = localFont({
  variable: "--font-manrope",
  src: [
    { path: "../assets/fonts/manrope-normal-200-800.woff2", weight: "200 800", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

const figtree = localFont({
  variable: "--font-figtree",
  src: [
    { path: "../assets/fonts/figtree-normal-300-900.woff2", weight: "300 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

const publicSans = localFont({
  variable: "--font-public-sans",
  src: [
    { path: "../assets/fonts/public-sans-normal-100-900.woff2", weight: "100 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

// ── Mono catalog (preload: false) ──
const firaCode = localFont({
  variable: "--font-fira-code",
  src: [
    { path: "../assets/fonts/fira-code-normal-300-700.woff2", weight: "300 700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

const sourceCodePro = localFont({
  variable: "--font-source-code-pro",
  src: [
    { path: "../assets/fonts/source-code-pro-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

const ibmPlexMono = localFont({
  variable: "--font-ibm-plex-mono",
  src: [
    { path: "../assets/fonts/ibm-plex-mono-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-normal-500.woff2", weight: "500", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-normal-600.woff2", weight: "600", style: "normal" },
    { path: "../assets/fonts/ibm-plex-mono-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

const robotoMono = localFont({
  variable: "--font-roboto-mono",
  src: [
    { path: "../assets/fonts/roboto-mono-normal-100-700.woff2", weight: "100 700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

const spaceMono = localFont({
  variable: "--font-space-mono",
  src: [
    { path: "../assets/fonts/space-mono-normal-400.woff2", weight: "400", style: "normal" },
    { path: "../assets/fonts/space-mono-normal-700.woff2", weight: "700", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

const inconsolata = localFont({
  variable: "--font-inconsolata",
  src: [
    { path: "../assets/fonts/inconsolata-normal-200-900.woff2", weight: "200 900", style: "normal" },
  ],
  preload: false,
  adjustFontFallback: "Arial",
  declarations: [{ prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

/** Every declared font instance — order is irrelevant; the layout just
 *  needs all `.variable` classes on the same element. */
const ALL_FONTS = [
  ebGaramond,
  inter,
  jetbrainsMono,
  geistSans,
  geistMono,
  fredoka,
  instrumentSerif,
  fraunces,
  roboto,
  openSans,
  lato,
  sourceSans3,
  notoSans,
  ibmPlexSans,
  workSans,
  dmSans,
  manrope,
  figtree,
  publicSans,
  firaCode,
  sourceCodePro,
  ibmPlexMono,
  robotoMono,
  spaceMono,
  inconsolata,
];

/** Space-joined `.variable` classes for the root <html> element. */
export const fontVariables = ALL_FONTS.map((f) => f.variable).join(" ");
