import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";

import {
  CLIENT_V1_HPKE_VECTOR_PATH,
  CLIENT_V1_HPKE_VECTOR_SHA256_PATH,
  clientV1HpkeVectorSha256,
  renderClientV1HpkeVector,
} from "./export-client-v1-hpke-vectors.mjs";

const gitAttributes = readFileSync(new URL("../.gitattributes", import.meta.url), "utf8");

function runExporter(...args) {
  return spawnSync(
    process.execPath,
    ["scripts/export-client-v1-hpke-vectors.mjs", ...args],
    { cwd: process.cwd(), encoding: "utf8" },
  );
}

function withTrackedVectorsRestored(run) {
  const vectorBytes = readFileSync(CLIENT_V1_HPKE_VECTOR_PATH);
  const digestBytes = readFileSync(CLIENT_V1_HPKE_VECTOR_SHA256_PATH);
  try {
    return run();
  } finally {
    writeFileSync(CLIENT_V1_HPKE_VECTOR_PATH, vectorBytes);
    writeFileSync(CLIENT_V1_HPKE_VECTOR_SHA256_PATH, digestBytes);
  }
}

test("documents the normative vector paths and LF normalization", () => {
  assert.equal(
    CLIENT_V1_HPKE_VECTOR_PATH,
    path.join(
      process.cwd(),
      "src",
      "lib",
      "server",
      "client-v1",
      "hpke-bound-v1-vectors.json",
    ),
  );
  assert.equal(
    CLIENT_V1_HPKE_VECTOR_SHA256_PATH,
    path.join(
      process.cwd(),
      "src",
      "lib",
      "server",
      "client-v1",
      "hpke-bound-v1-vectors.sha256",
    ),
  );
  for (const rule of [
    "src/lib/server/client-v1/hpke-bound-v1-vectors.json text eol=lf",
    "src/lib/server/client-v1/hpke-bound-v1-vectors.sha256 text eol=lf",
  ]) {
    assert.ok(
      gitAttributes.split(/\r?\n/u).includes(rule),
      `.gitattributes must include: ${rule}`,
    );
  }
});

test("renders recursively sorted two-space JSON with one LF and exact SHA-256", () => {
  const rendered = renderClientV1HpkeVector({
    z: { b: 2, a: 1 },
    a: [{ d: 4, c: 3 }],
  });
  assert.equal(
    rendered,
    '{\n'
      + '  "a": [\n'
      + '    {\n'
      + '      "c": 3,\n'
      + '      "d": 4\n'
      + '    }\n'
      + '  ],\n'
      + '  "z": {\n'
      + '    "a": 1,\n'
      + '    "b": 2\n'
      + '  }\n'
      + '}\n',
  );
  assert.equal(
    clientV1HpkeVectorSha256(rendered),
    `${createHash("sha256").update(rendered).digest("hex")}\n`,
  );
});

test("checks generated bytes without rewriting either committed file", () => {
  const beforeVector = readFileSync(CLIENT_V1_HPKE_VECTOR_PATH);
  const beforeDigest = readFileSync(CLIENT_V1_HPKE_VECTOR_SHA256_PATH);
  const result = runExporter("--check");
  assert.equal(result.status, 0, result.stderr || result.stdout);
  assert.deepEqual(readFileSync(CLIENT_V1_HPKE_VECTOR_PATH), beforeVector);
  assert.deepEqual(readFileSync(CLIENT_V1_HPKE_VECTOR_SHA256_PATH), beforeDigest);
});

test("fails read-only validation when vector or digest bytes are stale", () => {
  withTrackedVectorsRestored(() => {
    const vectorBytes = readFileSync(CLIENT_V1_HPKE_VECTOR_PATH);
    writeFileSync(
      CLIENT_V1_HPKE_VECTOR_PATH,
      `${vectorBytes.toString("utf8").replace(/\n$/u, "")} stale\n`,
    );
    const staleVector = runExporter("--check");
    assert.notEqual(staleVector.status, 0);
    assert.match(
      staleVector.stderr || staleVector.stdout,
      /Client v1 HPKE vector fixture is stale/u,
    );
  });

  withTrackedVectorsRestored(() => {
    writeFileSync(CLIENT_V1_HPKE_VECTOR_SHA256_PATH, `${"0".repeat(64)}\n`);
    const staleDigest = runExporter("--check");
    assert.notEqual(staleDigest.status, 0);
    assert.match(
      staleDigest.stderr || staleDigest.stdout,
      /Client v1 HPKE vector fixture is stale/u,
    );
  });
});

test("writes deterministic vector and digest bytes across consecutive atomic exports", () => {
  withTrackedVectorsRestored(() => {
    const first = runExporter();
    assert.equal(first.status, 0, first.stderr || first.stdout);
    const firstVector = readFileSync(CLIENT_V1_HPKE_VECTOR_PATH, "utf8");
    const firstDigest = readFileSync(CLIENT_V1_HPKE_VECTOR_SHA256_PATH, "utf8");

    const second = runExporter();
    assert.equal(second.status, 0, second.stderr || second.stdout);
    const secondVector = readFileSync(CLIENT_V1_HPKE_VECTOR_PATH, "utf8");
    const secondDigest = readFileSync(CLIENT_V1_HPKE_VECTOR_SHA256_PATH, "utf8");

    assert.equal(firstVector, secondVector);
    assert.equal(firstDigest, secondDigest);
    assert.equal(firstDigest, clientV1HpkeVectorSha256(firstVector));
    assert.match(firstDigest, /^[0-9a-f]{64}\n$/u);
  });
});
